#!/usr/bin/env zsh

brew install neovide fzf ag git-delta

# Install VIM plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

ln -s ~/dev/personal/dotfiles/nvim ~/.config/nvim
ln -s ~/dev/personal/dotfiles/zshrc ~/.zshrc
ln -s ~/dev/personal/dotfiles/zsh ~/.zsh
ln -s ~/dev/personal/vscode/tmux.conf ~/.tmux.conf
ln -s ~/dev/personal/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
