#!/usr/bin/env zsh

autoload -U colors
colors

setopt PROMPT_SUBST
setopt TRANSIENT_RPROMPT
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY